# site settings
title: Ile-de-France Planets
subtitle:
name: Ile-de-France Planets
description: We are a community of planetary scientists that works in Paris and the surrounding region of Ile-de-France.
baseurl:  # the subpath of your site, e.g. /blog
url: https://www.ile-de-france-planets.fr
logo1: Ile-de-france
logo2: Planets

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Mastodon: https://astrodon.social/@IDF_Planets
  Keybase: https://keybase.io/team/idf_planets
  Matrix: https://matrix.to/#/#IDF-Planets:matrix.org
  GitHub: https://github.com/idf-planets
  Email: mailto:&#105;&#100;&#102;&#45;&#112;&#108;&#97;&#110;&#101;&#116;&#115;&#46;&#107;&#57;&#48;&#53;&#105;&#64;&#97;&#108;&#101;&#101;&#97;&#115;&#46;&#99;&#111;&#109;
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

plugins:
  - jekyll-feed

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
