# site settings
title: Ile-de-France Planets
subtitle:
name: Ile-de-France Planets
description: We are a community of planetary scientists that works in Paris and the surrounding region of Ile-de-France.
baseurl:  # the subpath of your site, e.g. /blog
url: https://www.ile-de-france-planets.fr
logo1: Ile-de-france
logo2: Planets

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Mastodon: https://solarsystem.social/@IDF_Planets
  Matrix: https://matrix.to/#/#IDF-Planets:matrix.org
  GitHub: https://github.com/idf-planets
  Email: mailto:&#109;&#97;&#114;&#107;&#46;&#119;&#105;&#101;&#99;&#122;&#111;&#114;&#101;&#107;&#64;&#105;&#112;&#103;&#112;&#46;&#102;&#114;
  GitLab:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-link-attributes

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md

# -----------------------------------------------------------------------------
# Set defaults for jekyll-link-attributes pluggin
# -----------------------------------------------------------------------------
external_links:
  enabled: true
  rel: external noreferrer noopener
  target: _blank
